kind: pipeline
name: default

trigger:
  branch:
    - master
    - alpha
    - beta
    - rc
  event:
    - push

steps:
  - name: install
    image: node:current-alpine
    commands:
      - yarn --frozen-lockfile

  - name: lint
    image: node:current-alpine
    commands:
      - yarn lint:check

  - name: test
    image: node:current-alpine
    commands:
      - yarn test

  # - name: code-coverage
  #   image: node:current-alpine
  #   environment:
  #     CODECOV_TOKEN:
  #       from_secret: CODECOV_TOKEN
  #   commands:
  #     - apk add --no-cache --no-progress git
  #     - yarn global add codecov
  #     - codecov -f coverage/lcov.info

  - name: build
    image: node:current-alpine
    commands:
      - yarn build

  - name: semantic-release
    image: cenk1cenk2/drone-semantic-release
    settings:
      mode: release
      git_method: gh
      git_user_email:
        from_secret: GITHUB_USERNAME
      github_token:
        from_secret: GITHUB_TOKEN
      npm_token:
        from_secret: NPM_TOKEN
      update_readme_toc: true
    when:
      branch:
        - master
        - alpha
        - beta
        - rc
      event:
        - push

  - name: trigger
    image: plugins/downstream
    settings:
      server: https://drone.kilic.dev
      token:
        from_secret: drone_token
      deploy: production
      last_successful: true
      repositories:
        - cenk1cenk2/nuxt-docs@master

image_pull_secrets:
  - dockerconfigjson
