---
stages:
  - install
  - build
  - docs
  - publish

variables:
  NODE_VERSION: 18-alpine
  NODE_TEST_COMMAND: test

include:
  - project: devops/pipes
    file: /templates/node.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/node-run.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/semantic-release.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/docker-build-internal.gitlab-ci.yml

test:
  parallel:
    matrix:
      - NODE_VERSION: 18-alpine
      - NODE_VERSION: 16-alpine

vuepress:
  stage: docs
  extends: .node-run
  variables:
    NODE_COMMAND_SCRIPT: docs:build
  artifacts:
    paths:
      - ./docs/.vuepress/dist
  needs:
    - install
  dependencies:
    - install
  only:
    refs:
      - master
      - main

docker-build-docs:
  stage: publish
  extends: .docker-build-internal
  variables:
    DOCKERFILE_NAME: Dockerfile
    DOCKERFILE_CONTEXT: ./docs
    DOCKER_IMAGE_INTERNAL_NAME: docs-listr2
    DOCKER_IMAGE_TAGS: latest
  needs:
    - vuepress
  dependencies:
    - vuepress
  only:
    refs:
      - master
      - main

semantic-release:
  stage: publish
  extends: .semantic-release
  needs:
    - build
    - lint
    - test
  dependencies:
    - install
    - build
