---
stages:
  - install
  - build
  - docs
  - publish

variables:
  NODE_VERSION: 18-alpine
  NODE_TEST_COMMAND: test

include:
  - project: devops/pipes
    file: /templates/node.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/node-run.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/semantic-release.gitlab-ci.yml

test:
  parallel:
    matrix:
      - NODE_VERSION: 18-alpine
      - NODE_VERSION: 16-alpine

vuepress:
  stage: docs
  extends: .node-run
  variables:
    NODE_COMMAND_SCRIPT: docs:build
  artifacts:
    paths:
      - docs/.vuepress/dist
  only:
    refs:
      - master
      - main

docker-build:
  stage: publish
  extends: .docker-build-internal
  variables:
    DOCKERFILE_NAME: Dockerfile
    DOCKERFILE_CONTEXT: docs
    DOCKER_IMAGE_TAGS: latest
  dependencies:
    - vuepress
  only:
    refs:
      - master
      - main
      # TODO: REMOVE ME AFTERWARDS THE UPSTREAM RELEASE
      - beta
