name: Documentation
description: Request documentation.
title: '[Documentation]: '
labels: ['docs']
assignees:
  - cenk1cenk2
body:
  - type: textarea
    id: request
    attributes:
      label: Documentation Request
      description: Please describe what should be described in the documentation?
    validations:
      required: true

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight
      description: By submitting this issue, you agree that you have gone through the given requirements.
      options:
        - label: Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
          required: true

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation request template!

        If you have any further thing to add like the proposed specification of the request, now is the time!
